CREATE TABLE `survey_responses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`profession` enum('NUR','RAD','MT','PHAR','PT','OT','RT','DT','SLP','CP') NOT NULL,
	`respondent_name` varchar(255) NOT NULL,
	`title` varchar(255) NOT NULL,
	`department` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`epa_design_completion` int NOT NULL,
	`epa_count` varchar(50) NOT NULL,
	`epa_entrustment_level` int NOT NULL,
	`epa_milestone_description` int NOT NULL,
	`epa_teacher_understanding` int NOT NULL,
	`epa_challenges` text,
	`epa_support` text,
	`tool_minicex` int NOT NULL,
	`tool_dops` int NOT NULL,
	`tool_msf` int NOT NULL,
	`tool_calibration` varchar(50) NOT NULL,
	`tool_feedback_quality` int NOT NULL,
	`tool_feedback_timing` varchar(50) NOT NULL,
	`tool_challenges` text,
	`ccc_establishment` varchar(50) NOT NULL,
	`ccc_member_count` varchar(50) NOT NULL,
	`ccc_frequency` varchar(50) NOT NULL,
	`ccc_clarity` int NOT NULL,
	`ccc_prescription` varchar(50) NOT NULL,
	`ccc_challenges` text,
	`eport_implementation` varchar(50) NOT NULL,
	`eport_type` text,
	`eport_functionality` int NOT NULL,
	`eport_satisfaction` int NOT NULL,
	`eport_mobile` varchar(50) NOT NULL,
	`eport_suggestions` text,
	`training_completion` varchar(50) NOT NULL,
	`training_topics` text,
	`training_methods` text,
	`training_engagement` int NOT NULL,
	`training_needs` text,
	`learner_understanding` int NOT NULL,
	`learner_engagement` int NOT NULL,
	`learner_satisfaction` int NOT NULL,
	`learner_effectiveness` int NOT NULL,
	`learner_feedback` text,
	`overall_progress` int NOT NULL,
	`challenge_ranking` text,
	`success_stories` text,
	`suggestions` text,
	`epa_avg` float NOT NULL,
	`tool_avg` float NOT NULL,
	`ccc_avg` float NOT NULL,
	`eport_avg` float NOT NULL,
	`training_avg` float NOT NULL,
	`learner_avg` float NOT NULL,
	`overall_avg` float NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `survey_responses_id` PRIMARY KEY(`id`)
);
